version: "3.7"
services:
  ruby:
    container_name: rack_backend
    build: .
    command: bundle exec rackup -p 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
      - data-tmp:/app/tmp
volumes:
  data-tmp:
    driver: local
